// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "starships-api",
    "version": "1"
  },
  "paths": {
    "/films/{id}": {
      "get": {
        "summary": "getFilmByid",
        "description": "",
        "operationId": "getFilmByid.get.films/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/postFilme"
            }
          },
          "default": {
            "description": "default response"
          }
        }
      }
    },
    "/films/": {
      "post": {
        "summary": "postFilm",
        "description": "",
        "operationId": "postFilm.post.films/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postFilme"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "putFilm",
        "description": "",
        "operationId": "putFilm.put.films/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postFilme"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deleteFilm",
        "description": "",
        "operationId": "deleteFilm.delete.films/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/deleteFilme"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "postFilme": {
      "properties": {
        "titulo": {
          "title": "postFilme.titulo",
          "type": "string"
        },
        "episodio_id": {
          "title": "postFilme.episodio_id",
          "type": "number"
        },
        "texto_de_apertura": {
          "title": "postFilme.texto_de_apertura",
          "type": "string"
        },
        "director": {
          "title": "postFilme.director",
          "type": "string"
        },
        "productor": {
          "title": "postFilme.productor",
          "type": "string"
        },
        "fecha_de_estreno": {
          "title": "postFilme.fecha_de_estreno",
          "type": "string"
        },
        "personajes": {
          "items": {
            "type": "string"
          },
          "title": "postFilme.personajes",
          "type": "array"
        },
        "planetas": {
          "items": {
            "type": "string"
          },
          "title": "postFilme.planetas",
          "type": "array"
        },
        "naves_espaciales": {
          "items": {
            "type": "string"
          },
          "title": "postFilme.naves_espaciales",
          "type": "array"
        },
        "vehiculos": {
          "items": {
            "type": "string"
          },
          "title": "postFilme.vehiculos",
          "type": "array"
        },
        "especies": {
          "items": {
            "type": "string"
          },
          "title": "postFilme.especies",
          "type": "array"
        },
        "url": {
          "title": "postFilme.url",
          "type": "string"
        },
        "creado": {
          "title": "postFilme.creado",
          "type": "string"
        },
        "editado": {
          "title": "postFilme.editado",
          "type": "string"
        }
      },
      "required": [
        "titulo",
        "episodio_id",
        "texto_de_apertura",
        "director",
        "productor",
        "fecha_de_estreno",
        "personajes",
        "planetas",
        "naves_espaciales",
        "vehiculos",
        "especies",
        "url",
        "creado",
        "editado"
      ],
      "additionalProperties": false,
      "title": "postFilme",
      "type": "object"
    },
    "deleteFilme": {
      "properties": {
        "episodio_id": {
          "title": "deleteFilme.episodio_id",
          "type": "number"
        }
      },
      "required": [
        "episodio_id"
      ],
      "additionalProperties": false,
      "title": "deleteFilme",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};